export const StackRoutes = {
  knowledge: {
    main: "Knowledge",
    showReactInfo: "Knowledge Show React User",
    detail: "Knowledge Detail",
    friendInfo: "Knowledge Friend Profile",
    knowledgeForUser: "Knowledge Friend Knowledge",
    statusForUser: "Knowledge Friend Status",
    comment: "Knowledge Comment",
  },
  status: {
    main: "Status",
    showReactInfo: "Status Show React User",
    detail: "Status Knowledge Detail",
    friendInfo: "Status Friend Profile",
    knowledgeForUser: "Status Friend Knowledge",
    statusForUser: "Status Friend Status",
    comment: "Status Comment",
  },
  search: {
    main: "Search Screen",
    showReactInfo: "Search Show React User",
    detail: "Search Detail Knowledge",
    friendInfo: "Search Friend Profile",
    knowledgeForUser: "Search Friend Knowledge",
    statusForUser: "Search Friend Status",
    comment: "Search Comment",
  },
  notification: {
    knowledge: {
      main: "Knowledge Notification",
      showReactInfo: "Knowledge Notification Show React User",
      detail: "Knowledge Notification Detail Knowledge",
      friendInfo: "Knowledge Notification Friend Profile",
      knowledgeForUser: "Knowledge Notification Friend Knowledge",
      statusForUser: "Knowledge Notification Friend Status",
      comment: "Knowledge Notification Comment",
    },
    status: {
      main: "Status Notification",
      showReactInfo: "Status Notification Show React User",
      detail: "Status Notification Detail Knowledge",
      friendInfo: "Status Notification Friend Profile",
      knowledgeForUser: "Status Notification Friend Knowledge",
      statusForUser: "Status Notification Friend Status",
      comment: "Status Notification Comment",
      detailStatus: "Status Notification Detail Status",
    },
  },
  userInformation: {
    knowledge: {
      main: "Knowledge User",
      showReactInfo: "Knowledge User Info Show React User",
      detail: "Knowledge User Info Detail Knowledge",
      friendInfo: "Knowledge User Info Friend Profile",
      knowledgeForUser: "Knowledge User Info Friend Knowledge",
      statusForUser: "Knowledge User Info Friend Status",
      comment: "Knowledge User Info Comment",
      edit: "Knowledge User Info Edit Knowledge",
    },
    status: {
      main: "Status User",
      showReactInfo: "Status User Info Show React User",
      detail: "Status User Info Detail Knowledge",
      friendInfo: "Status User Info Friend Profile",
      knowledgeForUser: "Status User Info Friend Knowledge",
      statusForUser: "Status User Info Friend Status",
      comment: "Status User Info Comment",
      detailStatus: "Status User Info Detail Status",
      edit: "Status User Info Edit Status",
    },
  },
};
